# Generated by Django 3.0.5 on 2020-04-12 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('accepted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('booking_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=80)),
                ('city_address', models.CharField(max_length=80)),
                ('state_address', models.CharField(max_length=80)),
                ('country_address', models.CharField(max_length=80)),
                ('institute_type', models.CharField(max_length=80)),
                ('student_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InstituteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_type', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.FloatField()),
                ('paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Majors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=12)),
                ('insitute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Institute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('trip_expense', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('institutes', models.ManyToManyField(through='travel_agency.Booking', to='travel_agency.Institute')),
                ('trip_organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TripRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Traveler')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Traveler')),
            ],
        ),
        migrations.AddField(
            model_name='traveler',
            name='trips',
            field=models.ManyToManyField(through='travel_agency.TripRegistration', to='travel_agency.Trip'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=12)),
                ('grade_level', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
                ('declared_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Majors')),
                ('traveler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Traveler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestForProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('submission_date', models.DateField()),
                ('projected_date', models.DateField()),
                ('rfp_status', models.CharField(max_length=80)),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('accepted_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Institute')),
                ('trips', models.ManyToManyField(through='travel_agency.Bid', to='travel_agency.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('payment_type', models.CharField(max_length=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Invoice')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.PaymentStatus')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.PaymentPlan'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Trip'),
        ),
        migrations.CreateModel(
            name='InstituteFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('passport', models.CharField(max_length=80)),
                ('phone_number', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=80)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Department')),
                ('traveler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Traveler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Institute'),
        ),
        migrations.AddField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Trip'),
        ),
        migrations.AddField(
            model_name='bid',
            name='rfp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.RequestForProposal'),
        ),
        migrations.AddField(
            model_name='bid',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_agency.Trip'),
        ),
    ]
